package edu.epam.task6.controller.command;

import edu.epam.task6.model.entity.UserRole;

import java.util.List;

import static edu.epam.task6.model.entity.UserRole.ADMIN;
import static edu.epam.task6.model.entity.UserRole.USER;
import static edu.epam.task6.model.entity.UserRole.VISITOR;

public enum CommandType {
    DEFAULT (ADMIN, USER, VISITOR),
    TO_ABOUT_US_PAGE (ADMIN, USER, VISITOR),
    TO_CATALOG_PAGE (ADMIN, USER, VISITOR),
    TO_ALL_CATALOG_PAGE (ADMIN),
    TO_LOCKED_CATALOG_PAGE (ADMIN),
    TO_PROPOSAL_CATALOG_PAGE (ADMIN),
    TO_HOME_PAGE (ADMIN, USER, VISITOR),
    TO_LOGIN_PAGE (ADMIN, USER, VISITOR),
    TO_ORDERS_PAGE (ADMIN, USER),
    TO_CREATE_ORDER_PAGE (ADMIN, USER),
    TO_ACTIVE_ORDERS_PAGE (ADMIN),
    TO_COMPLETED_ORDERS_PAGE (ADMIN),
    TO_PROFILE_PAGE (ADMIN, USER),
    TO_PROPOSAL_PAGE (ADMIN, USER),
    TO_REGISTER_PAGE(ADMIN, USER, VISITOR),
    TO_ALL_USERS_PAGE (ADMIN),
    TO_ACTIVE_USERS_PAGE (ADMIN),
    TO_BLOCKED_USERS_PAGE (ADMIN),
    TO_BLOCK_USER_PAGE (ADMIN),
    TO_UNBLOCK_USER_PAGE (ADMIN),
    TO_ADD_TATTOO_PAGE (ADMIN),
    TO_BLOCK_TATTOO_PAGE (ADMIN),
    TO_UNBLOCK_TATTOO_PAGE (ADMIN),
    TO_APPROVE_TATTOO_PAGE (ADMIN),
    TO_CODE_PAGE (ADMIN, USER, VISITOR),

    TO_FIND_ORDER_BY_ID_PAGE (ADMIN, USER),
    TO_FIND_ORDER_BY_STATUS_PAGE (ADMIN, USER),
    TO_FIND_ORDER_BY_LOGIN_PAGE (ADMIN),

    TO_FIND_USER_BY_ID_PAGE (ADMIN),
    TO_FIND_USER_BY_LOGIN_PAGE (ADMIN),
    TO_FIND_USERS_BY_NAME_PAGE (ADMIN),
    TO_FIND_USERS_BY_SURNAME_PAGE (ADMIN),

    TO_FIND_TATTOO_BY_ID_PAGE (ADMIN, USER, VISITOR),
    TO_FIND_TATTOO_BY_NAME_PAGE (ADMIN, USER, VISITOR),
    TO_FIND_TATTOO_BY_PLACE_PAGE (ADMIN, USER, VISITOR),
    TO_FIND_TATTOO_BY_PRICE_RANGE_PAGE (ADMIN, USER, VISITOR),

    TO_CHANGE_EMAIL_PAGE (ADMIN, USER),
    TO_CHANGE_PASSWORD_PAGE (ADMIN, USER),
    TO_CHANGE_NAME_PAGE (ADMIN, USER),
    TO_CHANGE_SURNAME_PAGE (ADMIN, USER),
    TO_CHANGE_BALANCE_PAGE (USER),
    TO_CHANGE_USER_STATUS_PAGE (ADMIN),
    TO_CHANGE_RATING_PAGE (USER),

    CHANGE_EMAIL (ADMIN, USER),
    CHANGE_NAME (ADMIN, USER),
    CHANGE_SURNAME (ADMIN, USER),
    CHANGE_PASSWORD (ADMIN, USER),
    CHANGE_BALANCE (USER),
    CHANGE_USER_STATUS (ADMIN),
    CHANGE_TATTOO_STATUS (ADMIN),
    CHANGE_LANGUAGE (ADMIN, USER, VISITOR),
    CHANGE_RATING (USER),

    REGISTER_PERSON (VISITOR),
    CODE_ENTRY (VISITOR),
    LOGIN_PERSON (ADMIN, USER, VISITOR),
    LOGOUT_PERSON (ADMIN, USER),
    ADD_TATTOO (ADMIN, USER),
    APPROVE_TATTOO (ADMIN),
    CANCEL_ORDER (ADMIN, USER),
    CREATE_ORDER (ADMIN, USER),
    COMPLETE_ORDER(ADMIN),
    CREATE_COMMENT (ADMIN, USER),
    DELETE_COMMENT (ADMIN);

    private List<UserRole> roles;

    CommandType(UserRole... roles) {
        this.roles = List.of(roles);
    }

    public boolean isContainRole(UserRole userRole) {
        return roles.stream().anyMatch(role -> role == userRole);
    }
}
